package com.example.collins.navigation

const val HOME_URL = "home"
const val CITIES_URL = "cities"
const val DESTINATION_URL = "destination"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val SPLASH_URL = "start"
const val FIRST_URL = "landin"
const val MAIN_URL = "main"
const val CONTACT_URL = "main"
const val CATEGORIES_URL = "attractions"
const val WILDLIFE_URL = "list"
const val HERITAGE_URL = "heritage"
const val LOCATION_URL = "location"